#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "GParted" {
  set root=(hd0,1)
  set isofile="/boot/grml/gparted-live-1.2.0-1-amd64.iso"
  loopback loop $isofile
  linux (loop)/live/vmlinuz boot=live config union=overlay username=user components noswap noeject vga=788 ip= net.ifnames=0 toram=filesystem.squashfs findiso=$isofile
  initrd (loop)/live/initrd.img
}
menuentry "Eteindre" {
  halt
}
